"use client"

import { useForm } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { taskSchema, type TaskFormData } from "@/src/lib/validations/service"
import type { Task } from "@/src/types"

const mockTechnicians = [
  { id: "t1", name: "Tom Wilson", specialization: "HVAC" },
  { id: "t2", name: "Jane Cooper", specialization: "Smart Home" },
  { id: "t3", name: "Alex Martinez", specialization: "General" },
]

const timeSlots = [
  "08:00 - 10:00",
  "09:00 - 11:00",
  "10:00 - 12:00",
  "11:00 - 13:00",
  "13:00 - 15:00",
  "14:00 - 16:00",
  "15:00 - 17:00",
  "16:00 - 18:00",
]

const mockTasks: Record<string, Task> = {
  task1: {
    id: "task1",
    title: "AC Maintenance - John Smith",
    description: "Regular maintenance checkup for Air Conditioner Pro 5000.",
    technicianId: "t1",
    status: "pending",
    scheduledDate: "2024-12-15",
    timeSlot: "09:00 - 11:00",
    isAutoGenerated: true,
  },
  task2: {
    id: "task2",
    title: "Thermostat Setup - Sarah Johnson",
    description: "Install and configure Smart Thermostat X.",
    technicianId: "t2",
    status: "in-progress",
    scheduledDate: "2024-12-15",
    timeSlot: "11:00 - 13:00",
    isAutoGenerated: false,
  },
}

interface TaskEditFormProps {
  taskId: string
}

export function TaskEditForm({ taskId }: TaskEditFormProps) {
  const router = useRouter()
  const task = mockTasks[taskId]

  const {
    register,
    handleSubmit,
    setValue,
    watch,
    formState: { errors, isSubmitting },
  } = useForm<TaskFormData>({
    resolver: zodResolver(taskSchema),
    defaultValues: task
      ? {
          title: task.title,
          description: task.description || "",
          scheduledDate: task.scheduledDate,
          timeSlot: task.timeSlot,
          technicianId: task.technicianId,
        }
      : undefined,
  })

  const selectedTimeSlot = watch("timeSlot")
  const selectedTechnician = watch("technicianId")

  const onSubmit = async (data: TaskFormData) => {
    console.log("Updated task data:", data)
    router.push(`/admin/tasks/${taskId}`)
  }

  if (!task) {
    return (
      <Card className="bg-white shadow-sm">
        <CardContent className="py-12 text-center">
          <p className="text-muted-foreground">Task not found</p>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card className="bg-white shadow-sm">
      <CardHeader>
        <CardTitle className="font-heading text-xl font-semibold text-[#0A2540]">Edit Task Details</CardTitle>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="title" className="text-[#333333]">
              Task Title
            </Label>
            <Input
              id="title"
              {...register("title")}
              placeholder="Enter task title"
              className="border-border bg-white focus:border-[#00C49A] focus:ring-[#00C49A]"
            />
            {errors.title && <p className="text-sm text-destructive">{errors.title.message}</p>}
          </div>

          <div className="space-y-2">
            <Label htmlFor="description" className="text-[#333333]">
              Description
            </Label>
            <Textarea
              id="description"
              {...register("description")}
              placeholder="Describe the task..."
              rows={4}
              className="border-border bg-white focus:border-[#00C49A] focus:ring-[#00C49A]"
            />
            {errors.description && <p className="text-sm text-destructive">{errors.description.message}</p>}
          </div>

          <div className="grid gap-6 sm:grid-cols-3">
            <div className="space-y-2">
              <Label htmlFor="scheduledDate" className="text-[#333333]">
                Scheduled Date
              </Label>
              <Input
                id="scheduledDate"
                type="date"
                {...register("scheduledDate")}
                className="border-border bg-white focus:border-[#00C49A] focus:ring-[#00C49A]"
              />
              {errors.scheduledDate && <p className="text-sm text-destructive">{errors.scheduledDate.message}</p>}
            </div>

            <div className="space-y-2">
              <Label className="text-[#333333]">Time Slot</Label>
              <Select value={selectedTimeSlot} onValueChange={(value) => setValue("timeSlot", value)}>
                <SelectTrigger className="bg-white">
                  <SelectValue placeholder="Select time" />
                </SelectTrigger>
                <SelectContent>
                  {timeSlots.map((slot) => (
                    <SelectItem key={slot} value={slot}>
                      {slot}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label className="text-[#333333]">Assign Technician</Label>
              <Select value={selectedTechnician} onValueChange={(value) => setValue("technicianId", value)}>
                <SelectTrigger className="bg-white">
                  <SelectValue placeholder="Select technician" />
                </SelectTrigger>
                <SelectContent>
                  {mockTechnicians.map((tech) => (
                    <SelectItem key={tech.id} value={tech.id}>
                      {tech.name} ({tech.specialization})
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="flex items-center justify-end gap-3 pt-4">
            <Button
              type="button"
              variant="outline"
              onClick={() => router.back()}
              className="border-[#0A2540] text-[#0A2540] hover:bg-[#0A2540] hover:text-white bg-transparent"
            >
              Cancel
            </Button>
            <Button type="submit" disabled={isSubmitting} className="bg-[#00C49A] text-white hover:bg-[#00a883]">
              {isSubmitting ? "Saving..." : "Save Changes"}
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  )
}
