"use client"

import { useState } from "react"
import { useRouter, useParams } from "next/navigation"
import { ArrowLeft, Edit, CheckCircle, XCircle, Clock, Play } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { StatusBadge } from "@/src/components/ui/status-badge"
import type { Task } from "@/src/types"

const mockTasks: Record<string, Task> = {
  task1: {
    id: "task1",
    title: "AC Maintenance - John Smith",
    description:
      "Regular maintenance checkup for Air Conditioner Pro 5000. Check filters, refrigerant levels, and overall system performance.",
    technicianId: "t1",
    technician: {
      id: "t1",
      name: "Tom Wilson",
      email: "tom@company.com",
      phone: "+1 (555) 987-6543",
      specialization: "HVAC",
      isActive: true,
    },
    serviceRequestId: "s1",
    status: "pending",
    scheduledDate: "2024-12-15",
    timeSlot: "09:00 - 11:00",
    isAutoGenerated: true,
  },
  task2: {
    id: "task2",
    title: "Thermostat Setup - Sarah Johnson",
    description: "Install and configure Smart Thermostat X with WiFi connectivity and app setup.",
    technicianId: "t2",
    technician: {
      id: "t2",
      name: "Jane Cooper",
      email: "jane@company.com",
      phone: "+1 (555) 876-5432",
      specialization: "Smart Home",
      isActive: true,
    },
    status: "in-progress",
    scheduledDate: "2024-12-15",
    timeSlot: "11:00 - 13:00",
    isAutoGenerated: false,
  },
  task3: {
    id: "task3",
    title: "Heating Repair - Mike Davis",
    description: "Fix heating unit not reaching target temperature. Diagnose and repair as needed.",
    technicianId: "t1",
    technician: {
      id: "t1",
      name: "Tom Wilson",
      email: "tom@company.com",
      phone: "+1 (555) 987-6543",
      specialization: "HVAC",
      isActive: true,
    },
    serviceRequestId: "s3",
    status: "completed",
    scheduledDate: "2024-12-14",
    timeSlot: "14:00 - 16:00",
    isAutoGenerated: true,
  },
  task4: {
    id: "task4",
    title: "Filter Replacement - Emily Brown",
    description: "Replace air filters in Air Conditioner Pro 5000 unit.",
    technicianId: "t3",
    technician: {
      id: "t3",
      name: "Alex Martinez",
      email: "alex@company.com",
      phone: "+1 (555) 765-4321",
      specialization: "General",
      isActive: true,
    },
    serviceRequestId: "s4",
    status: "pending",
    scheduledDate: "2024-12-16",
    timeSlot: "10:00 - 12:00",
    isAutoGenerated: true,
  },
}

const getStatusVariant = (status: string) => {
  switch (status) {
    case "completed":
      return "success"
    case "in-progress":
      return "info"
    case "pending":
      return "default"
    case "cancelled":
      return "error"
    default:
      return "default"
  }
}

const statusOptions = [
  { value: "pending", label: "Pending", icon: Clock },
  { value: "in-progress", label: "In Progress", icon: Play },
  { value: "completed", label: "Completed", icon: CheckCircle },
  { value: "cancelled", label: "Cancelled", icon: XCircle },
]

export function TaskDetail() {
  const router = useRouter()
  const params = useParams()
  const taskId = params.id as string
  const task = mockTasks[taskId]
  const [status, setStatus] = useState(task?.status || "pending")

  const handleStatusChange = async (newStatus: string) => {
    setStatus(newStatus)
    console.log("Status updated to:", newStatus)
  }

  if (!task) {
    return (
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => router.back()}
            className="text-[#0A2540] hover:bg-[#F6F9FC]"
          >
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <h1 className="font-heading text-2xl font-bold text-[#0A2540]">Task Not Found</h1>
        </div>
        <Card className="bg-white shadow-sm">
          <CardContent className="py-12 text-center">
            <p className="text-muted-foreground">The requested task could not be found.</p>
            <Button
              onClick={() => router.push("/admin/tasks")}
              className="mt-4 bg-[#00C49A] text-white hover:bg-[#00a883]"
            >
              Back to Tasks
            </Button>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" onClick={() => router.back()} className="text-[#0A2540] hover:bg-[#F6F9FC]">
          <ArrowLeft className="h-5 w-5" />
        </Button>
        <div className="flex-1">
          <div className="flex items-center gap-3">
            <h1 className="font-heading text-2xl font-bold text-[#0A2540]">{task.title}</h1>
            <StatusBadge status={status} variant={getStatusVariant(status)} />
            {task.isAutoGenerated && (
              <span className="rounded-full bg-[#0A2540]/10 px-2.5 py-0.5 text-xs font-medium text-[#0A2540]">
                Auto-generated
              </span>
            )}
          </div>
          <p className="text-sm text-muted-foreground">
            Scheduled: {new Date(task.scheduledDate).toLocaleDateString()} | {task.timeSlot}
          </p>
        </div>
        <Button
          variant="outline"
          onClick={() => router.push(`/admin/tasks/${task.id}/edit`)}
          className="border-[#0A2540] text-[#0A2540] hover:bg-[#0A2540] hover:text-white bg-transparent"
        >
          <Edit className="mr-2 h-4 w-4" />
          Edit Task
        </Button>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        <Card className="bg-white shadow-sm lg:col-span-2">
          <CardHeader>
            <CardTitle className="font-heading text-lg font-semibold text-[#0A2540]">Task Details</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <p className="text-sm font-medium text-muted-foreground">Description</p>
              <p className="text-[#333333]">{task.description}</p>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-sm font-medium text-muted-foreground">Scheduled Date</p>
                <p className="text-[#333333]">{new Date(task.scheduledDate).toLocaleDateString()}</p>
              </div>
              <div>
                <p className="text-sm font-medium text-muted-foreground">Time Slot</p>
                <p className="text-[#333333]">{task.timeSlot}</p>
              </div>
            </div>
            {task.serviceRequestId && (
              <div>
                <p className="text-sm font-medium text-muted-foreground">Related Service Request</p>
                <Button
                  variant="link"
                  onClick={() => router.push(`/admin/services/${task.serviceRequestId}`)}
                  className="h-auto p-0 text-[#00C49A] hover:text-[#00a883]"
                >
                  View Service Request
                </Button>
              </div>
            )}
          </CardContent>
        </Card>

        <div className="space-y-6">
          <Card className="bg-white shadow-sm">
            <CardHeader>
              <CardTitle className="font-heading text-lg font-semibold text-[#0A2540]">Update Status</CardTitle>
            </CardHeader>
            <CardContent>
              <Select value={status} onValueChange={handleStatusChange}>
                <SelectTrigger className="bg-white">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {statusOptions.map((option) => (
                    <SelectItem key={option.value} value={option.value}>
                      <div className="flex items-center gap-2">
                        <option.icon className="h-4 w-4" />
                        {option.label}
                      </div>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </CardContent>
          </Card>

          <Card className="bg-white shadow-sm">
            <CardHeader>
              <CardTitle className="font-heading text-lg font-semibold text-[#0A2540]">Assigned Technician</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {task.technician ? (
                <div
                  onClick={() => router.push(`/admin/technicians/${task.technicianId}`)}
                  className="cursor-pointer rounded-lg border border-border p-4 transition-all hover:border-[#00C49A]/30 hover:bg-[#F6F9FC]"
                >
                  <p className="font-medium text-[#0A2540]">{task.technician.name}</p>
                  <p className="text-sm text-muted-foreground">{task.technician.specialization}</p>
                  <p className="text-sm text-muted-foreground">{task.technician.email}</p>
                  <p className="text-sm text-muted-foreground">{task.technician.phone}</p>
                </div>
              ) : (
                <p className="text-muted-foreground">No technician assigned</p>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
