"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { Plus, ChevronLeft, ChevronRight, CalendarDays, LayoutGrid } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { StatusBadge } from "@/src/components/ui/status-badge"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog"
import { cn } from "@/lib/utils"
import type { Task } from "@/src/types"

const today = new Date()
const formatDate = (daysOffset: number) => {
  const date = new Date(today)
  date.setDate(today.getDate() + daysOffset)
  return date.toISOString().split("T")[0]
}

const mockTasks: Task[] = [
  {
    id: "task1",
    title: "AC Maintenance - John Smith",
    description: "Regular maintenance checkup for Air Conditioner Pro 5000",
    technicianId: "t1",
    technician: { id: "t1", name: "Tom Wilson", email: "", phone: "", specialization: "HVAC", isActive: true },
    serviceRequestId: "s1",
    status: "pending",
    scheduledDate: formatDate(0), // Today
    timeSlot: "09:00 - 11:00",
    isAutoGenerated: true,
  },
  {
    id: "task2",
    title: "Thermostat Setup - Sarah Johnson",
    description: "Install and configure Smart Thermostat X",
    technicianId: "t2",
    technician: { id: "t2", name: "Jane Cooper", email: "", phone: "", specialization: "Smart Home", isActive: true },
    status: "in-progress",
    scheduledDate: formatDate(0), // Today
    timeSlot: "11:00 - 13:00",
    isAutoGenerated: false,
  },
  {
    id: "task3",
    title: "Heating Repair - Mike Davis",
    description: "Fix heating unit not reaching target temperature",
    technicianId: "t1",
    technician: { id: "t1", name: "Tom Wilson", email: "", phone: "", specialization: "HVAC", isActive: true },
    serviceRequestId: "s3",
    status: "completed",
    scheduledDate: formatDate(-1), // Yesterday
    timeSlot: "14:00 - 16:00",
    isAutoGenerated: true,
  },
  {
    id: "task4",
    title: "Filter Replacement - Emily Brown",
    description: "Replace air filters in Air Conditioner Pro 5000",
    technicianId: "t3",
    technician: {
      id: "t3",
      name: "Alex Martinez",
      email: "",
      phone: "",
      specialization: "General",
      isActive: true,
    },
    serviceRequestId: "s4",
    status: "pending",
    scheduledDate: formatDate(1), // Tomorrow
    timeSlot: "10:00 - 12:00",
    isAutoGenerated: true,
  },
  {
    id: "task5",
    title: "System Inspection - David Wilson",
    description: "Annual system inspection and diagnostics",
    technicianId: "t2",
    technician: { id: "t2", name: "Jane Cooper", email: "", phone: "", specialization: "Smart Home", isActive: true },
    status: "pending",
    scheduledDate: formatDate(3),
    timeSlot: "09:00 - 11:00",
    isAutoGenerated: false,
  },
  {
    id: "task6",
    title: "Duct Cleaning - Lisa Anderson",
    description: "Complete duct cleaning and sanitization",
    technicianId: "t1",
    technician: { id: "t1", name: "Tom Wilson", email: "", phone: "", specialization: "HVAC", isActive: true },
    status: "pending",
    scheduledDate: formatDate(0), // Today
    timeSlot: "14:00 - 16:00",
    isAutoGenerated: true,
  },
  {
    id: "task7",
    title: "AC Unit Installation - Robert Taylor",
    description: "New AC unit installation at residential property",
    technicianId: "t3",
    technician: {
      id: "t3",
      name: "Alex Martinez",
      email: "",
      phone: "",
      specialization: "General",
      isActive: true,
    },
    status: "pending",
    scheduledDate: formatDate(5),
    timeSlot: "08:00 - 12:00",
    isAutoGenerated: false,
  },
  {
    id: "task8",
    title: "Emergency Repair - Karen White",
    description: "Emergency cooling system repair",
    technicianId: "t1",
    technician: { id: "t1", name: "Tom Wilson", email: "", phone: "", specialization: "HVAC", isActive: true },
    status: "in-progress",
    scheduledDate: formatDate(1), // Tomorrow
    timeSlot: "14:00 - 16:00",
    isAutoGenerated: false,
  },
]

const getStatusVariant = (status: string) => {
  switch (status) {
    case "completed":
      return "success"
    case "in-progress":
      return "info"
    case "pending":
      return "default"
    case "cancelled":
      return "error"
    default:
      return "default"
  }
}

type ViewMode = "weekly" | "monthly"

export function TaskList() {
  const router = useRouter()
  const [currentDate, setCurrentDate] = useState(new Date())
  const [viewMode, setViewMode] = useState<ViewMode>("weekly")
  const [selectedDate, setSelectedDate] = useState<Date | null>(null)

  const formatDateStr = (date: Date) => date.toISOString().split("T")[0]

  const getWeekDays = () => {
    const days = []
    const startOfWeek = new Date(currentDate)
    startOfWeek.setDate(currentDate.getDate() - currentDate.getDay())

    for (let i = 0; i < 7; i++) {
      const day = new Date(startOfWeek)
      day.setDate(startOfWeek.getDate() + i)
      days.push(day)
    }
    return days
  }

  const getMonthDays = () => {
    const year = currentDate.getFullYear()
    const month = currentDate.getMonth()
    const firstDay = new Date(year, month, 1)
    const lastDay = new Date(year, month + 1, 0)
    const days: (Date | null)[] = []

    for (let i = 0; i < firstDay.getDay(); i++) {
      days.push(null)
    }

    for (let i = 1; i <= lastDay.getDate(); i++) {
      days.push(new Date(year, month, i))
    }

    return days
  }

  const weekDays = getWeekDays()
  const monthDays = getMonthDays()

  const getTasksForDate = (date: Date) => {
    return mockTasks.filter((task) => task.scheduledDate === formatDateStr(date))
  }

  const prevWeek = () => {
    const newDate = new Date(currentDate)
    newDate.setDate(currentDate.getDate() - 7)
    setCurrentDate(newDate)
  }

  const nextWeek = () => {
    const newDate = new Date(currentDate)
    newDate.setDate(currentDate.getDate() + 7)
    setCurrentDate(newDate)
  }

  const prevMonth = () => {
    const newDate = new Date(currentDate)
    newDate.setMonth(currentDate.getMonth() - 1)
    setCurrentDate(newDate)
  }

  const nextMonth = () => {
    const newDate = new Date(currentDate)
    newDate.setMonth(currentDate.getMonth() + 1)
    setCurrentDate(newDate)
  }

  const goToToday = () => {
    setCurrentDate(new Date())
  }

  const handleDateClick = (date: Date) => {
    setSelectedDate(date)
  }

  const dayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]

  return (
    <div className="space-y-4 md:space-y-6">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
        <div className="flex items-center gap-2 md:gap-3">
          <Button
            variant="outline"
            size="icon"
            onClick={viewMode === "weekly" ? prevWeek : prevMonth}
            className="h-8 w-8 md:h-9 md:w-9 border-[#0A2540] text-[#0A2540] hover:bg-[#0A2540] hover:text-white bg-transparent"
          >
            <ChevronLeft className="h-4 w-4" />
          </Button>
          <Button
            variant="outline"
            onClick={goToToday}
            className="border-[#0A2540] text-[#0A2540] hover:bg-[#0A2540] hover:text-white bg-transparent text-sm"
          >
            Today
          </Button>
          <Button
            variant="outline"
            size="icon"
            onClick={viewMode === "weekly" ? nextWeek : nextMonth}
            className="h-8 w-8 md:h-9 md:w-9 border-[#0A2540] text-[#0A2540] hover:bg-[#0A2540] hover:text-white bg-transparent"
          >
            <ChevronRight className="h-4 w-4" />
          </Button>
          <span className="ml-1 md:ml-2 font-heading text-base md:text-lg font-semibold text-[#0A2540]">
            {viewMode === "weekly"
              ? weekDays[0].toLocaleDateString("en-US", { month: "long", year: "numeric" })
              : currentDate.toLocaleDateString("en-US", { month: "long", year: "numeric" })}
          </span>
        </div>

        <div className="flex items-center gap-2 md:gap-3">
          <div className="flex items-center rounded-lg border border-border bg-white p-1">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setViewMode("weekly")}
              className={cn(
                "h-8 px-2 md:px-3 text-xs md:text-sm",
                viewMode === "weekly"
                  ? "bg-[#0A2540] text-white hover:bg-[#0A2540] hover:text-white"
                  : "text-[#0A2540] hover:bg-[#F6F9FC]",
              )}
            >
              <LayoutGrid className="mr-1 md:mr-2 h-4 w-4" />
              <span className="hidden sm:inline">Weekly</span>
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setViewMode("monthly")}
              className={cn(
                "h-8 px-2 md:px-3 text-xs md:text-sm",
                viewMode === "monthly"
                  ? "bg-[#0A2540] text-white hover:bg-[#0A2540] hover:text-white"
                  : "text-[#0A2540] hover:bg-[#F6F9FC]",
              )}
            >
              <CalendarDays className="mr-1 md:mr-2 h-4 w-4" />
              <span className="hidden sm:inline">Monthly</span>
            </Button>
          </div>

          <Button
            onClick={() => router.push("/admin/tasks/new")}
            className="bg-[#00C49A] text-white hover:bg-[#00a883] text-xs md:text-sm"
          >
            <Plus className="mr-1 md:mr-2 h-4 w-4" />
            <span className="hidden sm:inline">Create Task</span>
            <span className="sm:hidden">New</span>
          </Button>
        </div>
      </div>

      {viewMode === "weekly" ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-7 gap-3 md:gap-4">
          {weekDays.map((day) => {
            const tasks = getTasksForDate(day)
            const isToday = formatDateStr(day) === formatDateStr(new Date())

            return (
              <Card
                key={day.toISOString()}
                className={`min-h-[200px] lg:min-h-[300px] bg-white shadow-sm ${isToday ? "ring-2 ring-[#00C49A]" : ""}`}
              >
                <CardHeader className="pb-2">
                  <CardTitle className={`text-center ${isToday ? "text-[#00C49A]" : "text-[#0A2540]"}`}>
                    <div className="text-xs font-medium uppercase text-muted-foreground">{dayNames[day.getDay()]}</div>
                    <div className="font-heading text-xl md:text-2xl font-bold">{day.getDate()}</div>
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-2 p-2">
                  {tasks.map((task) => (
                    <div
                      key={task.id}
                      onClick={() => router.push(`/admin/tasks/${task.id}`)}
                      className="cursor-pointer rounded-lg border border-border p-2 transition-all duration-200 ease-out hover:border-[#00C49A]/30 hover:bg-[#F6F9FC]"
                    >
                      <div className="flex items-start justify-between gap-1">
                        <p className="text-xs font-medium text-[#0A2540] line-clamp-2">{task.title}</p>
                        {task.isAutoGenerated && (
                          <span className="shrink-0 rounded bg-[#0A2540]/10 px-1 py-0.5 text-[10px] text-[#0A2540]">
                            Auto
                          </span>
                        )}
                      </div>
                      <p className="mt-1 text-[10px] text-muted-foreground">{task.timeSlot}</p>
                      <div className="mt-1 flex items-center justify-between">
                        <span className="text-[10px] text-muted-foreground">{task.technician?.name}</span>
                        <StatusBadge
                          status={task.status}
                          variant={getStatusVariant(task.status)}
                          className="text-[10px] px-1.5 py-0"
                        />
                      </div>
                    </div>
                  ))}
                  {tasks.length === 0 && <p className="text-center text-xs text-muted-foreground py-4">No tasks</p>}
                </CardContent>
              </Card>
            )
          })}
        </div>
      ) : (
        // Monthly View
        <Card className="bg-white shadow-sm">
          <CardContent className="p-2 md:p-4">
            {/* Day headers */}
            <div className="grid grid-cols-7 gap-1 md:gap-2 mb-2">
              {dayNames.map((day) => (
                <div
                  key={day}
                  className="text-center text-xs md:text-sm font-medium text-muted-foreground py-1 md:py-2"
                >
                  <span className="hidden sm:inline">{day}</span>
                  <span className="sm:hidden">{day.charAt(0)}</span>
                </div>
              ))}
            </div>

            <div className="grid grid-cols-7 gap-1 md:gap-2">
              {monthDays.map((day, index) => {
                if (!day) {
                  return <div key={`empty-${index}`} className="h-16 md:h-24" />
                }

                const tasks = getTasksForDate(day)
                const isToday = formatDateStr(day) === formatDateStr(new Date())
                const hasTask = tasks.length > 0

                return (
                  <div
                    key={day.toISOString()}
                    onClick={() => handleDateClick(day)}
                    className={cn(
                      "h-16 md:h-24 rounded-lg border p-1 md:p-2 transition-all duration-200 cursor-pointer",
                      isToday ? "border-[#00C49A] bg-[#00C49A]/5" : "border-border",
                      "hover:border-[#00C49A]/50 hover:bg-[#F6F9FC]",
                    )}
                  >
                    <div
                      className={cn(
                        "text-xs md:text-sm font-medium mb-1",
                        isToday ? "text-[#00C49A]" : "text-[#0A2540]",
                      )}
                    >
                      {day.getDate()}
                    </div>
                    {hasTask && (
                      <div className="space-y-0.5 md:space-y-1">
                        {tasks.slice(0, 2).map((task) => (
                          <div
                            key={task.id}
                            className={cn(
                              "text-[8px] md:text-[10px] px-1 md:px-1.5 py-0.5 rounded truncate",
                              task.status === "completed"
                                ? "bg-green-100 text-green-700"
                                : task.status === "in-progress"
                                  ? "bg-blue-100 text-blue-700"
                                  : "bg-gray-100 text-gray-700",
                            )}
                          >
                            <span className="hidden md:inline">{task.title.split(" - ")[0]}</span>
                            <span className="md:hidden">{task.title.split(" ")[0]}</span>
                          </div>
                        ))}
                        {tasks.length > 2 && (
                          <div className="text-[8px] md:text-[10px] text-muted-foreground px-1">
                            +{tasks.length - 2}
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                )
              })}
            </div>
          </CardContent>
        </Card>
      )}

      <Dialog open={!!selectedDate} onOpenChange={() => setSelectedDate(null)}>
        <DialogContent className="max-w-lg max-h-[90vh] overflow-hidden flex flex-col">
          <DialogHeader>
            <DialogTitle className="font-heading text-[#0A2540]">
              Tasks for{" "}
              {selectedDate?.toLocaleDateString("en-US", {
                weekday: "long",
                month: "long",
                day: "numeric",
                year: "numeric",
              })}
            </DialogTitle>
            <DialogDescription>
              {selectedDate && getTasksForDate(selectedDate).length} task(s) scheduled
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-3 overflow-y-auto flex-1 pr-2">
            {selectedDate && getTasksForDate(selectedDate).length > 0 ? (
              getTasksForDate(selectedDate).map((task) => (
                <div
                  key={task.id}
                  onClick={() => {
                    setSelectedDate(null)
                    router.push(`/admin/tasks/${task.id}`)
                  }}
                  className="cursor-pointer rounded-lg border border-border p-4 transition-all duration-200 hover:border-[#00C49A]/30 hover:bg-[#F6F9FC]"
                >
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <p className="font-medium text-[#0A2540]">{task.title}</p>
                        {task.isAutoGenerated && (
                          <span className="shrink-0 rounded bg-[#0A2540]/10 px-1.5 py-0.5 text-[10px] text-[#0A2540]">
                            Auto
                          </span>
                        )}
                      </div>
                      <p className="text-sm text-muted-foreground mt-1 line-clamp-2">{task.description}</p>
                    </div>
                    <StatusBadge
                      status={task.status}
                      variant={getStatusVariant(task.status)}
                      className="flex-shrink-0"
                    />
                  </div>
                  <div className="flex items-center justify-between mt-3 pt-3 border-t border-border">
                    <span className="text-sm text-muted-foreground">
                      <span className="font-medium text-[#0A2540]">{task.technician?.name}</span>
                    </span>
                    <span className="text-sm text-muted-foreground">{task.timeSlot}</span>
                  </div>
                </div>
              ))
            ) : (
              <div className="text-center py-8">
                <p className="text-muted-foreground">No tasks scheduled for this date</p>
                <Button
                  onClick={() => {
                    setSelectedDate(null)
                    router.push("/admin/tasks/new")
                  }}
                  className="mt-4 bg-[#00C49A] text-white hover:bg-[#00a883]"
                >
                  <Plus className="mr-2 h-4 w-4" />
                  Create Task
                </Button>
              </div>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  )
}
