// Core Types for Admin Panel


export interface Category {
  id: string
  name: string
  description?: string
  createdAt: string
}

export interface Customer {
  id: string
  name: string
  email: string
  phone: string
  address: string
  addressType?: "apartment" | "rumah" | "company"
  status: "active" | "inactive" | "blacklisted"
  createdAt: string
  updatedAt?: string // Backend might not return this always if it's not setup
}

export interface CreateCustomerDTO {
  name: string
  email: string
  phone: string
  address: string
  addressType?: "apartment" | "rumah" | "company"
  status?: "active" | "inactive" | "blacklisted"
  password?: string
}

export interface UpdateCustomerDTO extends Partial<CreateCustomerDTO> {}

export interface Product {
  id: string
  name: string
  description?: string | null
  price?: number | null
  model?: string | null
  imageUrl?: string | null
  categoryId?: string | null
  category?: {
    id: string
    name: string
  } | null
  createdAt?: string | null
}

export interface CreateProductDTO {
  name: string
  description?: string
  price?: number
  model?: string
  imageUrl?: string
  categoryId?: string
}

export interface CustomerProduct {
  id: string
  customer_id: string
  product_catalog_id: string
  order_product_id?: string | null
  installation_technician_id?: string | null
  status: string
  quantity_owned: number
  cust_product_price?: number | null
  installation_date?: string | null
  installation_location?: string | null
  description?: string | null
  photo_url?: string | null
  notes?: string | null
  created_at: string

  // Enriched fields
  product_name?: string
  product_model?: string
  technician_name?: string
  contract_status?: string
}

export interface CreateCustomerProductDTO {
  customer_id: string;
  product_catalog_id: string;
  installation_technician_id?: string;
  installation_date?: string;
  installation_location?: string;
  cust_product_price?: number;
  quantity_owned?: number;
  status?: 'active' | 'inactive' | 'tradeIn';
  description?: string;
  photo_url?: string;
  notes?: string;
}

export interface UpdateCustomerProductDTO extends Partial<CreateCustomerProductDTO> {}

export interface Contract {
  id: string
  customerProductId: string
  customerProduct?: CustomerProduct
  startDate: string
  endDate: string
  status: "active" | "expired" | "pending"
  type: string
  value: number
  pdfUrl?: string
}

export interface ServiceRequest {
  id: string
  customerProductId: string
  customerProduct?: CustomerProduct
  status: "pending" | "scheduled" | "in-progress" | "completed" | "cancelled"
  description: string
  scheduledDate?: string
  technicianId?: string
  technician?: Technician
  createdAt: string
}

export interface ScheduleExpected {
  id: string
  serviceRequestId: string
  serviceRequest?: ServiceRequest
  expectedDate: string
  timeSlot: string
}

export interface ServiceLog {
  id: string
  serviceRequestId: string
  serviceRequest?: ServiceRequest
  technicianId: string
  technician?: Technician
  notes: string
  evidenceUrls: string[]
  completedAt: string
}

export interface Task {
  id: string
  title: string
  description: string
  technicianId?: string
  technician?: Technician
  serviceRequestId?: string
  status: "pending" | "in-progress" | "completed" | "cancelled"
  scheduledDate: string
  timeSlot?: string
  isAutoGenerated: boolean
}

export interface Technician {
  id: string
  name: string
  phone?: string | null
  photo_url?: string | null
  notes?: string | null
  created_at?: string | null
}

export interface Invoice {
  id: string
  customerId: string
  customer?: Customer
  type: "order" | "contract" | "service"
  referenceId: string
  amount: number
  status: "draft" | "sent" | "paid" | "overdue"
  dueDate: string
  createdAt: string
}

export interface ChatConversation {
  id: string
  customerId: string
  customer?: Customer
  lastMessage?: string
  lastMessageAt?: string
  unreadCount: number
}

export interface ChatMessage {
  id: string
  conversationId: string
  senderId: string
  senderType: "admin" | "customer"
  content: string
  attachmentUrl?: string
  createdAt: string
}

export interface MonthlyServiceSummary {
  totalServices: number
  completedServices: number
  pendingServices: number
  averageCompletionTime: number
}

export interface RevenueData {
  month: string
  revenue: number
}

export interface TechnicianPayout {
  technicianId: string
  technician: Technician
  tasksCompleted: number
  totalPayout: number
}
