// Core Types for Admin Panel

export interface Customer {
  id: string
  name: string
  email: string
  phone: string
  address: string
  createdAt: string
  updatedAt: string
}

export interface Product {
  id: string
  name: string
  description: string
  category: string
  price: number
  imageUrl?: string
}

export interface CustomerProduct {
  id: string
  customerId: string
  productId: string
  customer?: Customer
  product?: Product
  purchaseDate: string
  warrantyExpiry?: string
  serialNumber?: string
}

export interface Contract {
  id: string
  customerProductId: string
  customerProduct?: CustomerProduct
  startDate: string
  endDate: string
  status: "active" | "expired" | "pending"
  type: string
  value: number
  pdfUrl?: string
}

export interface ServiceRequest {
  id: string
  customerProductId: string
  customerProduct?: CustomerProduct
  status: "pending" | "scheduled" | "in-progress" | "completed" | "cancelled"
  description: string
  scheduledDate?: string
  technicianId?: string
  technician?: Technician
  createdAt: string
}

export interface ScheduleExpected {
  id: string
  serviceRequestId: string
  serviceRequest?: ServiceRequest
  expectedDate: string
  timeSlot: string
}

export interface ServiceLog {
  id: string
  serviceRequestId: string
  serviceRequest?: ServiceRequest
  technicianId: string
  technician?: Technician
  notes: string
  evidenceUrls: string[]
  completedAt: string
}

export interface Task {
  id: string
  title: string
  description: string
  technicianId?: string
  technician?: Technician
  serviceRequestId?: string
  status: "pending" | "in-progress" | "completed" | "cancelled"
  scheduledDate: string
  timeSlot?: string
  isAutoGenerated: boolean
}

export interface Technician {
  id: string
  name: string
  phone?: string | null
  photo_url?: string | null
  notes?: string | null
  created_at?: string | null
}

export interface Invoice {
  id: string
  customerId: string
  customer?: Customer
  type: "order" | "contract" | "service"
  referenceId: string
  amount: number
  status: "draft" | "sent" | "paid" | "overdue"
  dueDate: string
  createdAt: string
}

export interface ChatConversation {
  id: string
  customerId: string
  customer?: Customer
  lastMessage?: string
  lastMessageAt?: string
  unreadCount: number
}

export interface ChatMessage {
  id: string
  conversationId: string
  senderId: string
  senderType: "admin" | "customer"
  content: string
  attachmentUrl?: string
  createdAt: string
}

export interface MonthlyServiceSummary {
  totalServices: number
  completedServices: number
  pendingServices: number
  averageCompletionTime: number
}

export interface RevenueData {
  month: string
  revenue: number
}

export interface TechnicianPayout {
  technicianId: string
  technician: Technician
  tasksCompleted: number
  totalPayout: number
}
