"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { StatusBadge } from "@/src/components/ui/status-badge"
import { Mail, Phone, Briefcase, Calendar, CheckCircle } from "lucide-react"
import type { Technician, Task } from "@/src/types"

const mockTechnicians: Record<string, Technician> = {
  t1: {
    id: "t1",
    name: "Tom Wilson",
    email: "tom@company.com",
    phone: "+1 (555) 987-6543",
    specialization: "HVAC",
    isActive: true,
  },
  t2: {
    id: "t2",
    name: "Jane Cooper",
    email: "jane@company.com",
    phone: "+1 (555) 876-5432",
    specialization: "Smart Home",
    isActive: true,
  },
  t3: {
    id: "t3",
    name: "Alex Martinez",
    email: "alex@company.com",
    phone: "+1 (555) 765-4321",
    specialization: "General",
    isActive: true,
  },
  t4: {
    id: "t4",
    name: "Chris Johnson",
    email: "chris@company.com",
    phone: "+1 (555) 654-3210",
    specialization: "HVAC",
    isActive: false,
  },
}

const mockTasks: Task[] = [
  {
    id: "task1",
    title: "AC Maintenance - John Smith",
    description: "Regular maintenance checkup",
    technicianId: "t1",
    status: "pending",
    scheduledDate: "2024-12-15",
    timeSlot: "09:00 - 11:00",
    isAutoGenerated: true,
  },
  {
    id: "task2",
    title: "Heating Repair - Mike Davis",
    description: "Fix heating unit",
    technicianId: "t1",
    status: "completed",
    scheduledDate: "2024-12-14",
    timeSlot: "14:00 - 16:00",
    isAutoGenerated: true,
  },
]

const getStatusVariant = (status: string) => {
  switch (status) {
    case "completed":
      return "success"
    case "in-progress":
      return "info"
    case "pending":
      return "default"
    default:
      return "default"
  }
}

export function TechnicianDetail({ id }: { id: string }) {
  const technician = mockTechnicians[id]

  if (!technician) {
    return (
      <Card className="bg-white shadow-sm">
        <CardContent className="py-12 text-center">
          <p className="text-muted-foreground">Technician not found</p>
        </CardContent>
      </Card>
    )
  }

  const technicianTasks = mockTasks.filter((task) => task.technicianId === id)
  const completedTasks = technicianTasks.filter((t) => t.status === "completed").length
  const pendingTasks = technicianTasks.filter((t) => t.status === "pending").length

  return (
    <div className="space-y-6">
      <Card className="bg-white shadow-sm">
        <CardContent className="p-6">
          <div className="flex flex-col gap-6 sm:flex-row sm:items-start">
            <div className="flex h-20 w-20 items-center justify-center rounded-full bg-[#00C49A]/10 text-2xl font-bold text-[#00C49A]">
              {technician.name
                .split(" ")
                .map((n) => n[0])
                .join("")}
            </div>
            <div className="flex-1">
              <div className="flex items-center gap-3">
                <h2 className="font-heading text-2xl font-bold text-[#0A2540]">{technician.name}</h2>
                <StatusBadge
                  status={technician.isActive ? "Active" : "Inactive"}
                  variant={technician.isActive ? "success" : "error"}
                />
              </div>
              <span className="mt-2 inline-block rounded-full bg-[#0A2540]/10 px-3 py-1 text-sm font-medium text-[#0A2540]">
                {technician.specialization}
              </span>
              <div className="mt-4 grid gap-3 sm:grid-cols-2">
                <div className="flex items-center gap-2 text-muted-foreground">
                  <Mail className="h-4 w-4" />
                  <span>{technician.email}</span>
                </div>
                <div className="flex items-center gap-2 text-muted-foreground">
                  <Phone className="h-4 w-4" />
                  <span>{technician.phone}</span>
                </div>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="grid gap-6 sm:grid-cols-3">
        <Card className="bg-white shadow-sm">
          <CardContent className="p-6">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#00C49A]/10">
                <Briefcase className="h-5 w-5 text-[#00C49A]" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Total Tasks</p>
                <p className="font-heading text-2xl font-bold text-[#0A2540]">{technicianTasks.length}</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="bg-white shadow-sm">
          <CardContent className="p-6">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#00C49A]/10">
                <CheckCircle className="h-5 w-5 text-[#00C49A]" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Completed</p>
                <p className="font-heading text-2xl font-bold text-[#0A2540]">{completedTasks}</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="bg-white shadow-sm">
          <CardContent className="p-6">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-full bg-amber-500/10">
                <Calendar className="h-5 w-5 text-amber-500" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Pending</p>
                <p className="font-heading text-2xl font-bold text-[#0A2540]">{pendingTasks}</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card className="bg-white shadow-sm">
        <CardHeader>
          <CardTitle className="font-heading text-lg font-semibold text-[#0A2540]">Assigned Tasks</CardTitle>
        </CardHeader>
        <CardContent>
          {technicianTasks.length === 0 ? (
            <p className="py-8 text-center text-muted-foreground">No tasks assigned</p>
          ) : (
            <div className="space-y-3">
              {technicianTasks.map((task) => (
                <div
                  key={task.id}
                  className="flex items-center justify-between rounded-lg border border-border p-4 transition-all duration-200 hover:border-[#00C49A]/30 hover:bg-[#F6F9FC]"
                >
                  <div>
                    <p className="font-medium text-[#0A2540]">{task.title}</p>
                    <p className="text-sm text-muted-foreground">
                      {task.scheduledDate} | {task.timeSlot}
                    </p>
                  </div>
                  <StatusBadge status={task.status} variant={getStatusVariant(task.status)} />
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
